# Based on https://docs.haskellstack.org/en/stable/travis_ci/

sudo: false

language: generic

os:
  - osx
  - linux

env:
  - RESOLVER="lts-11.9"           # ghc 8.2.2
  - RESOLVER="nightly-2018-05-18" # ghc 8.4.2
  - RESOLVER="nightly"

matrix:
  allow_failures:
    # cf https://github.com/commercialhaskell/stack/issues/3472 : allow linux to fail for ghc < 8.4.1
    - os: linux
      env: RESOLVER="lts-11.9"
    - env: RESOLVER="nightly"
    # TODO remove once 'postgresql-simple' is 8.4.2 compatible
    - env: RESOLVER="nightly-2018-05-18"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libxcursor-dev
    - libxi-dev
    - libxinerama-dev
    - libxrandr-dev
    - libftgl-dev
    - libgmp-dev
    - portaudio19-dev
    # g++ versions before 7 won't work, as some needed C++14 features are not implemented.
    - g++-7
    - libstdc++-7-dev

cache:
  directories:
  - $HOME/.stack

# TODO test uninstall llvm then   brew install --with-toolchain llvm
before_install:

- set -ex

- |
  if [[ $TRAVIS_OS_NAME == 'linux' ]]
  then
    export CXX=g++-7
    export CC=gcc-7
    ${CXX} --version
    ${CC} --version
    sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-7 /usr/bin/gcc
    gcc --version
  fi
- |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]
  then
    brew bundle --verbose
    brew info llvm
    brew update
    brew upgrade llvm
    brew info llvm
    export PATH="/usr/local/opt/llvm/bin:$PATH"
  fi

- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- |
  if [ `uname` = "Darwin" ]
  then
    travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi

- set +ex

script:
- set -ex
- |
  echo "$(stack --resolver $RESOLVER exec -- which gcc)"
  echo "$(stack --resolver $RESOLVER exec -- gcc --version)"
- stack --no-terminal --resolver $RESOLVER build --install-ghc --only-dependencies -j2
- stack --no-terminal --resolver $RESOLVER test --pedantic --haddock --no-haddock-deps -j2
- set +ex
