# http://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-10.2

packages:
- './imj-prelude'
- './imj-base'
- './imj-benchmark'
- './imj-particlesystem'
- './imj-game-hamazed'
- './imj-measure-stdout'

- location:
    git: https://github.com/OlivierSohn/GLFW-b.git
    commit: c77bc69f740b7863a020a63531d0e181c465a50f
  extra-dep: true
- location:
    git: https://github.com/OlivierSohn/bindings-GLFW.git
    commit: f04f9cd23aab48ac4dcd456736d298ce863d905c
  extra-dep: true

extra-deps: []

flags: {}

extra-package-dbs: []

# for GC stats:
#   -with-rtsopts=-sstderr
#
# I added -fpedantic-bottoms to catch errors that are masked by the compiler
#   as explained in  https://ghc.haskell.org/trac/ghc/ticket/14521
ghc-options:
  "$locals": -threaded -fpedantic-bottoms -Wredundant-constraints -rtsopts -with-rtsopts=-maxN4 -fexcess-precision -optc-ffast-math
