# http://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-9.12

packages:
- '.'
- location:
    git: https://github.com/mpilgrem/ansi-terminal.git
    commit: 42f1dc8e8607ab33a62b187b0b5212b14f50b5aa
- location:
    git: https://gitlab.com/OlivierSohn/Ease.git
    commit: 1d1398100135fa6571f37ff00a9607e886773a6f

extra-deps:
- monadlist-0.0.2

flags: {}

extra-package-dbs: []

# for GC stats:
#   -with-rtsopts=-sstderr
#
# I added -fpedantic-bottoms to catch errors that are masked by the compiler
#   as explained in  https://ghc.haskell.org/trac/ghc/ticket/14521
ghc-options:
  "hamazed": -threaded -fpedantic-bottoms -rtsopts -with-rtsopts=-maxN4 -O2 -fexcess-precision -optc-ffast-math
