# http://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-11.5

packages:
- './imj-prelude'
- './imj-base'
- './imj-benchmark'
- './imj-particlesystem'
- './imj-game-hamazed'
- './imj-profile'
- './imj-measure-stdout'

- location:
    git: https://github.com/OlivierSohn/GLFW-b.git
    commit: b271c2dda33f3d2eccc49ecbac1a4257580acb52
  extra-dep: true
- location:
    git: https://github.com/OlivierSohn/clay.git
    commit: fabb12c7cffcf12d2eb51224409b1819f7cdd42f
  extra-dep: true
- location:
    git: https://github.com/OlivierSohn/mwc-random.git
    commit: 89a5657db7cf0a6b95a6fba8467445208f9313e6
  extra-dep: true

extra-deps:
- FTGL-2.1
- bindings-GLFW-3.2.1.0
# to build ghc-mod:
#- https://hackage.haskell.org/package/ghc-mod-5.9.0.0/candidate/ghc-mod-5.9.0.0.tar.gz
#- cabal-helper-0.8.0.0
#- extra-1.5.3
#- monad-journal-0.7.2
#- either-4.4.1.1
#allow-newer: true # for optparse-applicative, due to ghc-mod

flags: {}

extra-package-dbs: []

# for GC stats:
#   -with-rtsopts=-sstderr
#
# -with-rtsopts=-N : we use it just to set the parallel GC on, we will manually set the number of capabilities in the code.
#
# -fpedantic-bottoms : to catch errors that are masked by the compiler,
#   as explained in https://ghc.haskell.org/trac/ghc/ticket/14521
#
# -qa : makes the benchmarks on world creation slightly (~1%) faster.
#
# -feager-blackholing : removed since it is slower (3%) for world creation benchmarks.
ghc-options:
  "$locals": -threaded -fexcess-precision -optc-ffast-math -Wall -fpedantic-bottoms -Wredundant-constraints -rtsopts -with-rtsopts=-N -with-rtsopts=-qa

# Whenever an option here changes, the corresponding modules should be recompiled:
rebuild-ghc-options: true
