# http://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-10.2

packages:
- '.'

extra-deps: []

flags: {}

extra-package-dbs: []

# for GC stats:
#   -with-rtsopts=-sstderr
#
# I added -fpedantic-bottoms to catch errors that are masked by the compiler
#   as explained in  https://ghc.haskell.org/trac/ghc/ticket/14521
ghc-options:
  "$locals": -threaded -fpedantic-bottoms -Wredundant-constraints -rtsopts -with-rtsopts=-maxN4 -fexcess-precision -optc-ffast-math
